"""Keypoint-lattice detection (the keypoint->homography workflow).

Modern court detectors (Court R-CNN, CourtKeyNet) predict court keypoints,
enforce geometric consistency, then compute a homography. This is a
classical, training-free stand-in with the same output contract, so a learned
keypoint model can later drop into the same slot:

  keypoints    -> intersections of Hough H/V segments, classified by junction
                  structure (L / T / X, from how many painted arms leave the
                  point). A CNN's identity prediction is replaced by the type:
                  an observed junction can only LOSE arms to occlusion or
                  fragmentation, never gain them, so e.g. an X junction can
                  never sit on a court corner.
  consistency  -> enumerate junction "grid quads" (4 junctions produced by 2
                  H segments x 2 V segments) and only the model-lattice
                  assignments whose types are compatible at all four corners.
  homography   -> hypotheses verified by counting the model's 30 lattice
                  points that land on detected junctions, then least-squares
                  refit on all matched keypoint pairs.
"""

import itertools

import cv2
import numpy as np

from ..court.detector import _line_intersection, detect_court_line_segments
from . import model
from .hough_fit import _full_court_plausible

_ARMS = {"L": 2, "T": 3, "X": 4}
# Keys rounded to mm — LATTICE_POINTS is float32, the model constants are
# Python floats, and raw float keys would never match across the two.
_LATTICE_ARM_BY_XY = {
    (round(float(x), 3), round(float(y), 3)): _ARMS[t]
    for (x, y), t in zip(model.LATTICE_POINTS, model.LATTICE_TYPES)
}

# Model line pairs a (top, bottom) / (left, right) junction quad may span.
# Type constraints prune hard, so narrower quads are allowed than in
# hough_fit (the centre line is usable here — its junctions exist).
H_ASSIGNMENTS = [
    (ya, yb)
    for ya, yb in itertools.combinations(model.H_LINE_YS, 2)
    if yb - ya >= 3.9
]
V_ASSIGNMENTS = [
    (xa, xb)
    for xa, xb in itertools.combinations(model.V_LINE_XS, 2)
    if xb - xa >= 2.5
]


def _segment_arms(segment, point, arm_px, slack_px):
    """(arms, on_segment) — how many painted arms of *segment* leave *point*."""
    x1, y1, x2, y2 = segment["points"]
    start = np.array([x1, y1], dtype=np.float64)
    end = np.array([x2, y2], dtype=np.float64)
    direction = end - start
    length = np.linalg.norm(direction)
    if length < 1e-6:
        return 0, False
    direction /= length
    along = float(np.dot(np.asarray(point, dtype=np.float64) - start, direction))
    if along < -slack_px or along > length + slack_px:
        return 0, False
    return int(along > arm_px) + int(along < length - arm_px), True


def detect_junction_keypoints(horizontal, side, image_shape):
    """Candidate court keypoints: typed intersections of H and V segments.

    Returns a list of dicts with point / arms / type / strength and the
    indices of the segments that produced each junction (h_idx, v_idx).
    """
    height, width = image_shape[:2]
    margin = 0.06 * min(width, height)
    arm_px = max(10.0, 0.015 * min(width, height))
    slack_px = max(14.0, 0.02 * min(width, height))

    junctions = []
    for h_idx, h_seg in enumerate(horizontal):
        for v_idx, v_seg in enumerate(side):
            point = _line_intersection(h_seg["points"], v_seg["points"])
            if point is None:
                continue
            if not (-margin <= point[0] <= width - 1 + margin
                    and -margin <= point[1] <= height - 1 + margin):
                continue
            arms_h, on_h = _segment_arms(h_seg, point, arm_px, slack_px)
            arms_v, on_v = _segment_arms(v_seg, point, arm_px, slack_px)
            if not (on_h and on_v) or arms_h == 0 or arms_v == 0:
                continue
            arms = arms_h + arms_v
            junctions.append({
                "point": np.asarray(point, dtype=np.float64),
                "arms": arms,
                "type": {4: "X", 3: "T", 2: "L"}[arms],
                "strength": min(h_seg["length"], v_seg["length"]),
                "h_idx": h_idx,
                "v_idx": v_idx,
            })
    return junctions


def _grid_quads(junctions):
    """Junction quads generated by 2 H segments x 2 V segments, ordered
    (top-left, top-right, bottom-right, bottom-left) in segment terms."""
    by_pair = {(j["h_idx"], j["v_idx"]): j for j in junctions}
    h_ids = sorted({j["h_idx"] for j in junctions})
    v_ids = sorted({j["v_idx"] for j in junctions})
    quads = []
    for ha, hb in itertools.combinations(h_ids, 2):
        for va, vb in itertools.combinations(v_ids, 2):
            corners = [
                by_pair.get((ha, va)), by_pair.get((ha, vb)),
                by_pair.get((hb, vb)), by_pair.get((hb, va)),
            ]
            if all(c is not None for c in corners):
                quads.append(corners)
    return quads


def _order_canonical(quad):
    """Ensure (TL, TR, BR, BL) in image space: top pair above bottom pair,
    each pair left-to-right. Returns None if the quad isn't grid-like."""
    pts = np.array([c["point"] for c in quad])
    top_y = (pts[0, 1] + pts[1, 1]) / 2.0
    bottom_y = (pts[2, 1] + pts[3, 1]) / 2.0
    if bottom_y < top_y:
        quad = [quad[3], quad[2], quad[1], quad[0]]
        pts = pts[[3, 2, 1, 0]]
    if pts[0, 0] > pts[1, 0]:
        quad = [quad[1], quad[0], quad[3], quad[2]]
    return quad


def _junction_quad_ok(image_quad, image_shape):
    """Lighter gate than model.quad_plausible: junction grid quads between
    nearby court lines are legitimately small (half-court views especially),
    and wrong hypotheses are weeded out by lattice-inlier verification."""
    height, width = image_shape[:2]
    pts = np.array(image_quad, dtype=np.float32)
    if not np.isfinite(pts).all():
        return False
    if len(cv2.convexHull(pts)) != 4:
        return False
    if abs(cv2.contourArea(pts)) < width * height * 0.012:
        return False
    top_y = (pts[0, 1] + pts[1, 1]) / 2.0
    bottom_y = (pts[2, 1] + pts[3, 1]) / 2.0
    return bottom_y - top_y >= height * 0.06


def detect(image, judge, segments=None):
    """Return (homography or None, debug dict).

    segments: optional precomputed (horizontal, side, mask) from any front
    end in extraction.FRONT_ENDS; defaults to the HSV green-gated one.
    """
    horizontal, side, seg_mask = segments or detect_court_line_segments(image)
    debug = {"n_horizontal": len(horizontal), "n_side": len(side), "mask": seg_mask}
    if len(horizontal) < 2 or len(side) < 2:
        return None, debug

    junctions = detect_junction_keypoints(horizontal, side, image.shape)
    debug["n_keypoints"] = len(junctions)
    if len(junctions) < 4:
        return None, debug

    height, width = image.shape[:2]
    junction_pts = np.array([j["point"] for j in junctions])
    junction_arms = np.array([j["arms"] for j in junctions])
    lattice_arms = np.array([_ARMS[t] for t in model.LATTICE_TYPES])
    inlier_tol = max(6.0, 0.02 * min(width, height))

    best = None  # (inliers, -mean_dist, homography, matches)
    hypothesis_count = 0
    for quad in _grid_quads(junctions):
        quad = _order_canonical(quad)
        image_quad = np.array([c["point"] for c in quad], dtype=np.float32)
        if not _junction_quad_ok(image_quad, image.shape):
            continue
        for ya, yb in H_ASSIGNMENTS:
            for xa, xb in V_ASSIGNMENTS:
                model_xy = [(xa, ya), (xb, ya), (xb, yb), (xa, yb)]
                model_arm = [
                    _LATTICE_ARM_BY_XY.get((round(px, 3), round(py, 3)))
                    for px, py in model_xy
                ]
                if any(arm is None for arm in model_arm):
                    continue  # e.g. centre line x paired with a y it never reaches
                if any(c["arms"] > arm for c, arm in zip(quad, model_arm)):
                    continue  # junction shows more arms than that lattice point has
                homography = cv2.getPerspectiveTransform(
                    np.array(model_xy, dtype=np.float32), image_quad
                )
                hypothesis_count += 1
                if not _full_court_plausible(homography, image.shape):
                    continue

                projected, valid = model.project_points(homography, model.LATTICE_POINTS)
                if valid.sum() < 8:
                    continue
                distances = np.linalg.norm(
                    projected[valid][:, None, :] - junction_pts[None, :, :], axis=2
                )
                nearest = distances.argmin(axis=1)
                nearest_dist = distances[np.arange(len(nearest)), nearest]
                type_ok = junction_arms[nearest] <= lattice_arms[valid]
                inlier = (nearest_dist <= inlier_tol) & type_ok
                count = int(inlier.sum())
                if count < 4:
                    continue
                mean_dist = float(nearest_dist[inlier].mean())
                matches = (np.flatnonzero(valid)[inlier], nearest[inlier])
                if best is None or (count, -mean_dist) > (best[0], best[1]):
                    best = (count, -mean_dist, homography, matches)

    debug["hypotheses"] = hypothesis_count
    if best is None:
        return None, debug
    count, _neg, homography, (model_ids, junction_ids) = best
    debug["ransac_inliers"] = count

    # Least-squares refit on all matched keypoint pairs; keep it only if the
    # mask-support score doesn't regress.
    refined, _mask = cv2.findHomography(
        model.LATTICE_POINTS[model_ids].reshape(-1, 1, 2),
        junction_pts[junction_ids].reshape(-1, 1, 2).astype(np.float32),
        0,
    )
    if refined is not None and _full_court_plausible(refined, image.shape):
        if judge.score(refined)["line_f1"] >= judge.score(homography)["line_f1"]:
            homography = refined
    return homography, debug
